name: Generate JSDoc

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install JSDoc & Build Documentation
      run: |
        npm install -g jsdoc
        jsdoc README.md ./ -r -d docs

    # Tambahan: Commit & Push folder docs kembali ke repository
    - name: Commit & Push generated docs
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add docs/
        git commit -m "docs: update JSDoc documentation [skip ci]" || exit 0
        git push
